/* ========================================================================
 * Copyright 2014 horario
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 horario

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.horario.curso.master.logic.dto;

import co.edu.uniandes.csw.horario.seccion.logic.dto.SeccionDTO;
import co.edu.uniandes.csw.horario.curso.logic.dto.CursoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _CursoMasterDTO {

 
    protected CursoDTO cursoEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public CursoDTO getCursoEntity() {
        return cursoEntity;
    }

    public void setCursoEntity(CursoDTO cursoEntity) {
        this.cursoEntity = cursoEntity;
    }
    
    public List<SeccionDTO> createseccion_curs;
    public List<SeccionDTO> updateseccion_curs;
    public List<SeccionDTO> deleteseccion_curs;
    public List<SeccionDTO> listseccion_curs;	
	
	
	
    public List<SeccionDTO> getCreateseccion_curs(){ return createseccion_curs; };
    public void setCreateseccion_curs(List<SeccionDTO> createseccion_curs){ this.createseccion_curs=createseccion_curs; };
    public List<SeccionDTO> getUpdateseccion_curs(){ return updateseccion_curs; };
    public void setUpdateseccion_curs(List<SeccionDTO> updateseccion_curs){ this.updateseccion_curs=updateseccion_curs; };
    public List<SeccionDTO> getDeleteseccion_curs(){ return deleteseccion_curs; };
    public void setDeleteseccion_curs(List<SeccionDTO> deleteseccion_curs){ this.deleteseccion_curs=deleteseccion_curs; };
    public List<SeccionDTO> getListseccion_curs(){ return listseccion_curs; };
    public void setListseccion_curs(List<SeccionDTO> listseccion_curs){ this.listseccion_curs=listseccion_curs; };	
	
	
}

